# Stage 1: maven to install jar dependencies
FROM maven:3.8.5-openjdk-17 AS dependency-builder
WORKDIR /app

# download dependencies
COPY jars_flink_client/pom.xml .
RUN mvn dependency:copy-dependencies -DoutputDirectory=target/lib

# Stage 2: flink sql client
FROM cnfldemos/flink-kafka:1.19.1-scala_2.12-java17

# copy dependencies from stage 1
COPY --from=dependency-builder /app/target/lib /opt/flink/lib/
RUN chown -R flink:flink /opt/flink/lib/

# flink conf
COPY flink-conf.yaml /opt/flink/conf/flink-conf.yaml

CMD ["sh", "-c", "tail -f /dev/null"]