# Stage 1: Use a Maven image to download dependencies
FROM maven:3.8.5-openjdk-17 AS dependency-builder

WORKDIR /app

# Copy pom.xml to download dependencies
COPY jars_flink_client/pom.xml .
RUN mvn dependency:copy-dependencies -DoutputDirectory=target/lib

# Stage 2: Build the final image for the Flink SQL client
FROM cnfldemos/flink-kafka:1.19.1-scala_2.12-java17

# Copy the dependencies from the builder stage
COPY --from=dependency-builder /app/target/lib /opt/flink/lib/
RUN chown -R flink:flink /opt/flink/lib/

CMD ["sh", "-c", "tail -f /dev/null"]